apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tdxx
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-tdxx@sha256:6c4d657c0b570193f19ac074dd74a619451500e3d21cb0dd7e22a493f03cb9df
        name: my-nodejs
        resources: {}
status: {}
